on:
 push:
   branches: ['main']
 pull_request:
   branches: ['main']
   
 workflow_dispatch:
   
jobs:
   build:
      runs-on: ubuntu-latest
      
      steps:
         - uses: actions/checkout@v3
         
         - name: Run Environment
           run: 
              pip3 --version
              python3 -m venv environment
              source environment/bin/activate
              pip3 install -r requirements.txt
              behave --version    
             
 
